# Generated by Django 5.0.6 on 2024-05-22 08:38

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='')),
                ('image', models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='')),
            ],
        ),
    ]
